name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  intl: ^0.18.1
  weather: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/